version: "3.3"
services:
    database:
      image: mariadb
      container_name: sae_database
      restart: always
      networks:
        internal_network:
          ipv4_address: 172.16.1.20
      environment:
        MYSQL_ROOT_PASSWORD: toto
      volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        - ./custom-entrypoint.sh:/docker-entrypoint.sh
        - ./db_data:/var/lib/mysql
      ports:
        - "3306:3306"

    nats_server:
      image: nats
      restart: always
      container_name: sae_nats_server
      networks:
        internal_network:
          ipv4_address: 172.16.1.30
      ports:
        - "4222:4222"

networks:
    internal_network:
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: 172.16.1.0/24

